# 1. Conexão local na porta 5432, apontando para o banco que você acabou de criar
spring.datasource.url=jdbc:postgresql://localhost:5432/appointmentdb

# 2. Usuário padrão do Postgres e a senha que você escolheu na instalação
spring.datasource.username=postgres
spring.datasource.password=123

# 3. As regras do Hibernate para ele construir as tabelas para nós
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true